name: example
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  feedback:
    path: ../../feedback
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.21
  http: ^1.2.1
  path_provider: ^2.1.1
  share_plus: ^8.0.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
